import type { CSSProperties } from 'react'

export const editableRootStyle = {
  '--slot4-page-bg': '#0b0b0b',
  '--slot4-page-text': '#ffffffe6',
  '--slot4-panel-bg': '#141414',
  '--slot4-surface-bg': '#1d1d1d',
  '--slot4-muted-text': '#ffffffb3',
  '--slot4-soft-muted-text': '#ffffff80',
  '--slot4-accent': '#24d861',
  '--slot4-accent-fill': '#24d861',
  '--slot4-accent-soft': '#7aff9026',
  '--slot4-on-accent': '#0b0b0b',
  '--slot4-dark-bg': '#0b0b0b',
  '--slot4-dark-text': '#ffffff',
  '--slot4-media-bg': '#262626',
  '--slot4-cream': '#f0eeed',
  '--slot4-warm': '#141414',
  '--slot4-lavender': '#1f1f1f',
  '--slot4-gray': '#2d2d2d',
  '--slot4-yellow': '#dce233',
  '--slot4-purple': '#6624d8',
  '--slot4-pink': '#ff79fd',
  '--slot4-body-gradient': 'radial-gradient(circle at 50% 0%, rgba(36,216,97,0.12), transparent 38%), #0b0b0b',
  '--editable-page-bg': '#0b0b0b',
  '--editable-page-text': '#ffffffe6',
  '--editable-container': '1180px',
  '--editable-border': '#ffffff1a',
  '--editable-nav-bg': '#0b0b0b',
  '--editable-nav-text': '#ffffffe6',
  '--editable-nav-active': '#24d861',
  '--editable-nav-active-text': '#0b0b0b',
  '--editable-cta-bg': '#24d861',
  '--editable-cta-text': '#0b0b0b',
  '--editable-search-bg': '#141414',
  '--editable-footer-bg': '#0b0b0b',
  '--editable-footer-text': '#ffffffe6',
} as CSSProperties

export const editablePalette = {
  pageBg: 'bg-[var(--slot4-page-bg)]',
  pageText: 'text-[var(--slot4-page-text)]',
  panelBg: 'bg-[var(--slot4-panel-bg)]',
  panelText: 'text-[var(--slot4-page-text)]',
  surfaceBg: 'bg-[var(--slot4-surface-bg)]',
  surfaceText: 'text-[var(--slot4-page-text)]',
  mutedText: 'text-[var(--slot4-muted-text)]',
  softMutedText: 'text-[var(--slot4-soft-muted-text)]',
  accentText: 'text-[var(--slot4-accent)]',
  accentBg: 'bg-[var(--slot4-accent-fill)]',
  accentSoftBg: 'bg-[var(--slot4-accent-soft)]',
  accentSoftText: 'text-[var(--slot4-accent)]',
  onAccentText: 'text-[var(--slot4-on-accent)]',
  darkBg: 'bg-[var(--slot4-dark-bg)]',
  darkText: 'text-[var(--slot4-dark-text)]',
  mediaBg: 'bg-[var(--slot4-media-bg)]',
  creamBg: 'bg-[var(--slot4-cream)]',
  warmBg: 'bg-[var(--slot4-warm)]',
  lavenderBg: 'bg-[var(--slot4-lavender)]',
  grayBg: 'bg-[var(--slot4-gray)]',
  border: 'border-[var(--editable-border)]',
  darkBorder: 'border-white/10',
  shadow: 'shadow-[0_0_0_1px_rgba(255,255,255,0.04)]',
  shadowStrong: 'shadow-[0_30px_90px_rgba(0,0,0,0.35)]',
  overlay: 'bg-[linear-gradient(180deg,rgba(0,0,0,0.08),rgba(0,0,0,0.78))]',
} as const

export const editableDesignContract = {
  shell: {
    page: `min-h-screen ${editablePalette.pageBg} ${editablePalette.pageText}`,
    section: 'mx-auto w-full max-w-[var(--editable-container)] px-4 sm:px-6 lg:px-8',
    sectionY: 'py-16 sm:py-20 lg:py-[120px]',
  },
  layout: {
    safeGrid: 'grid gap-5 md:grid-cols-2 xl:grid-cols-3',
    featureGrid: 'grid gap-12 lg:grid-cols-[1.05fr_0.95fr] lg:items-center',
    rail: 'flex snap-x gap-5 overflow-x-auto pb-4 [scrollbar-width:none] [&::-webkit-scrollbar]:hidden',
    minRailCard: 'w-[280px] shrink-0 snap-start sm:w-[340px]',
  },
  type: {
    eyebrow: 'text-xs font-semibold tracking-[0.16em] text-[var(--slot4-accent)]',
    heroTitle: 'editable-display text-5xl leading-[1.02] tracking-[-0.04em] sm:text-6xl lg:text-[5rem]',
    sectionTitle: 'editable-display text-4xl leading-[1.08] tracking-[-0.035em] sm:text-5xl lg:text-[4rem]',
    body: 'text-base leading-8 text-[var(--slot4-muted-text)]',
    emphasis: 'editable-display italic text-[var(--slot4-page-text)]',
  },
  surface: {
    card: `rounded-[24px] border ${editablePalette.border} ${editablePalette.surfaceBg} ${editablePalette.shadow}`,
    soft: `rounded-[20px] border ${editablePalette.border} ${editablePalette.panelBg}`,
    dark: `rounded-[24px] ${editablePalette.darkBg} ${editablePalette.darkText} ${editablePalette.shadowStrong}`,
  },
  button: {
    primary: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-accent-fill)] px-7 py-3 text-sm font-semibold text-[var(--slot4-on-accent)] transition duration-300 hover:brightness-110',
    secondary: 'inline-flex items-center justify-center gap-2 rounded-full border border-[var(--editable-border)] bg-[var(--slot4-surface-bg)] px-7 py-3 text-sm font-semibold text-[var(--slot4-page-text)] transition duration-300 hover:border-[var(--slot4-accent)] hover:text-[var(--slot4-accent)]',
    accent: 'inline-flex items-center justify-center gap-2 rounded-full bg-[var(--slot4-yellow)] px-7 py-3 text-sm font-semibold text-black transition duration-300 hover:brightness-105',
    ghost: 'inline-flex items-center justify-center gap-2 rounded-full px-5 py-3 text-sm font-semibold text-[var(--slot4-muted-text)] transition duration-300 hover:text-[var(--slot4-page-text)]',
  },
  badge: {
    pill: 'inline-flex items-center gap-2 rounded-full border border-[var(--editable-border)] bg-white/5 px-3.5 py-1.5 text-xs font-semibold text-[var(--slot4-muted-text)]',
    accentPill: 'inline-flex items-center gap-2 rounded-full bg-[var(--slot4-accent-soft)] px-3.5 py-1.5 text-xs font-semibold text-[var(--slot4-accent)]',
  },
  media: {
    frame: `relative overflow-hidden rounded-[24px] ${editablePalette.mediaBg}`,
    frameFull: `relative overflow-hidden rounded-[24px] border ${editablePalette.border} ${editablePalette.mediaBg}`,
    ratio: 'aspect-[2/3]',
  },
  motion: {
    lift: 'transition duration-300 hover:-translate-y-1 hover:border-[var(--slot4-accent)]/45',
    fade: 'transition duration-300 hover:opacity-80',
    zoom: 'transition duration-700 group-hover:scale-[1.035]',
  },
} as const

export const aiLayoutRules = [
  'Reference-driven dark editorial resource library; update editableRootStyle first.',
  'Keep public pages focused on Reference Library resources.',
  'Contributor records remain direct-URL-only and are never surfaced in public navigation or feeds.',
  'Use pill CTAs, rounded dark panels, serif display hierarchy, and subtle lift motion.',
  'Keep dynamic fetching intact; never replace posts with mock arrays.',
] as const


